### ISSUE TITLE
SceneReference does not show up in UnityEvents

### ISSUE THREAD

**Issue by TheTrueDuck** [starikcetin/Eflatun.SceneReference#101] opened 2024-05-30 17:10 UTC
Right now, if you were to make a function with a SceneReference as a parameter, since SceenReference doesn't derive from UnityEngine.Object, it doesn't get shown as an option in UnityEvents (like a button's OnClick event). It would be nice to if it did :)

**Comment by starikcetin** [comment] 2024-05-30 20:58
Duplicate of #97.

**Closed by starikcetin** 2024-05-30 20:58 UTC
