### ISSUE TITLE
type is not a supported pptr value

### ISSUE THREAD

**Issue by RoxDevvv** [starikcetin/Eflatun.SceneReference#68] opened 2023-08-23 05:45 UTC
trying to call 
```
if (_field.objectReferenceValue != null) {
}
```
but throw error 
type is not a supported pptr value

**Comment by RoxDevvv** [comment] 2023-08-23 09:49
_field is SerializedProperty of `public SceneReference sceneReference;`
`SerializedProperty sceneReferenceProperty = pairProperty.FindPropertyRelative("sceneReference");`
am checking if it have value using `sceneReferenceProperty.objectReferenceValue`
checking if it null cause I wanna show error message in case other developers in my team forget to fill it

**Comment by starikcetin** [comment] 2023-08-23 11:11
That is not a supported use case, since you are reaching for the internals. And just checking for value will not be enough validation, as there are other possible problems. Can you try using the [Public Validation API](https://github.com/starikcetin/Eflatun.SceneReference#validation) instead?

**Comment by Ale1** [comment] 2023-08-23 11:54
@RoxDevvv .   BTW,  a property of type SceneReference when used as a serializedProperty will have property type "Generic", not "Object".  So makes sense that calling  MySceneRef.objectReferenceValue  throws that error (i.e its not a bug).

**Comment by starikcetin** [comment] 2023-08-23 16:54
I am closing this issue for now. If you don't manage to accomplish what you need with the validation API, then please open a new issue as a feature request with a detailed use case and we can discuss its viability.

**Closed by starikcetin** 2023-08-23 16:54 UTC
